// <auto-generated />
using System;
using ExpenseHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ExpenseHub.Api.Data.Migrations
{
    [DbContext(typeof(ExpenseHubDbContext))]
    partial class ExpenseHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseHub.Api.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DecidedById")
                        .HasMaxLength(450)
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("DATE");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("EH_EXPENSES", (string)null);
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EH_EXPENSE_CATEGORIES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hospedagem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Material de escritório"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Outros"
                        });
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.ExpenseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Changes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId", "OccurredAtUtc");

                    b.ToTable("EH_EXPENSE_HISTORY", (string)null);
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PaidById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.ToTable("EH_PAYMENT_RECORDS", (string)null);
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.Expense", b =>
                {
                    b.HasOne("ExpenseHub.Api.Domain.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.ExpenseHistory", b =>
                {
                    b.HasOne("ExpenseHub.Api.Domain.Expense", null)
                        .WithMany("History")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.PaymentRecord", b =>
                {
                    b.HasOne("ExpenseHub.Api.Domain.Expense", null)
                        .WithOne("Payment")
                        .HasForeignKey("ExpenseHub.Api.Domain.PaymentRecord", "ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseHub.Api.Domain.Expense", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
